<a href="https://colab.research.google.com/github/hilmi130904/Data_Mining/blob/main/Tugas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

data kita simpan di google drive dan kita akan panggil

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

data saya dalam bentuk excel

In [6]:
import pandas as pd
file_path='/content/drive/MyDrive/Data Mining/Kelulusan Test.xls'
df=pd.read_excel(file_path)

menampilkan data

In [7]:
df.head(50)

,NAMA,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
0,UNAMA,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.17,2.70,3.23,2.41,3.00,2.47,1.75,0.00,2.75,TEPAT
1,LEYLA TRIYANA PRATIWI,PEREMPUAN,MAHASISWA,26,BELUM MENIKAH,3.60,3.50,3.42,2.85,3.31,2.95,2.18,NaN,3.39,TEPAT
2,VERIS SOFIYAN PRAYOGA,LAKI - LAKI,MAHASISWA,29,BELUM MENIKAH,2.67,2.66,2.93,3.14,2.92,2.64,2.88,0.50,2.81,TEPAT
3,ADITYA AKBAR NUGRAHA,LAKI - LAKI,MAHASISWA,27,BELUM MENIKAH,2.48,2.86,2.09,2.55,2.55,2.43,2.55,2.17,2.82,TEPAT
4,ERNA EKA RIYANTI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.19,3.08,3.31,2.83,3.36,2.73,3.06,0.00,3.09,TEPAT
5,FARID DWI NORYANTO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.10,2.98,3.17,3.25,3.41,3.08,3.43,3.00,3.23,TEPAT
6,DAFIK HADI WINOTO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,2.98,2.68,2.23,2.86,2.25,2.64,1.52,2.10,2.54,TEPAT
7,WAHYU FITRIYANTO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.45,3.15,3.54,3.78,3.42,3.88,2.50,4.00,3.56,TEPAT
8,IMAM SURYO SUSANTO,LAKI - LAKI,MAHASISWA,26,BELUM MENIKAH,3.31,3.02,3.48,3.70,3.19,3.21,2.58,4.00,3.40,TEPAT
9,AHMAD SUTOPO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,2.62,2.73,2.11,3.36,2.79,3.17,2.45,0.00,2.97,TEPAT
10,HERI SUFA'AT,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.24,3.06,2.79,2.73,3.02,2.59,3.08,0.00,3.08,TEPAT
11,MURYA AMIEN NUR PRABOWO,LAKI - LAKI,MAHASISWA,26,BELUM MENIKAH,2.83,3.02,3.02,3.63,3.21,3.09,2.57,3.00,3.33,TEPAT
12,EDY PURNOMO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,2.83,3.00,2.54,3.36,2.79,3.28,3.28,3.00,3.15,TEPAT
13,DIDIK KURNIAWAN,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.00,3.08,3.02,3.07,2.88,2.76,3.00,2.50,2.92,TEPAT
14,LYDIA EVITA SANDRA DEWI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.52,3.52,3.31,3.33,3.30,2.94,3.46,0.00,3.26,TEPAT
15,DAVID KURNIAWAN,LAKI - LAKI,MAHASISWA,36,BELUM MENIKAH,2.29,0.50,0.16,0.32,1.13,0.37,0.28,0.11,1.02,TEPAT
16,DEVI KISTIANI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.52,3.46,3.69,3.41,3.40,0.00,0.00,NaN,3.43,TEPAT
17,ADI PURWADI,LAKI - LAKI,MAHASISWA,27,BELUM MENIKAH,2.60,2.91,2.66,2.91,3.25,2.88,2.83,0.00,2.86,TEPAT
18,ARIF WIBOWO,LAKI - LAKI,MAHASISWA,30,BELUM MENIKAH,2.52,2.59,2.11,3.00,2.73,2.50,2.48,0.00,2.68,TEPAT
19,NOVAZAEN DWI SAPUTRO,LAKI - LAKI,MAHASISWA,28,BELUM MENIKAH,2.79,3.05,3.21,2.92,3.41,2.86,2.50,0.00,3.04,TEPAT
20,MOHAMAD ADE FADHORI,LAKI - LAKI,MAHASISWA,30,BELUM MENIKAH,2.93,2.52,1.95,2.37,3.07,2.91,1.73,1.60,2.81,TEPAT
21,SUBAEDAH,PEREMPUAN,MAHASISWA,23,BELUM MENIKAH,3.52,3.48,3.71,3.83,3.25,3.65,2.33,3.50,3.56,TEPAT
22,DANI PRIMAYANTI,PEREMPUAN,MAHASISWA,24,BELUM MENIKAH,3.48,3.73,3.60,3.52,2.90,3.32,3.21,0.00,3.45,TEPAT
23,DERA BAHTIAR WIDIYANTO,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,2.52,3.30,3.79,3.71,3.65,2.10,3.59,4.00,3.52,TEPAT
24,MUKHAMAD YAHYA WICAKSONO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,2.45,2.66,2.93,3.08,3.29,3.18,2.10,3.00,3.10,TEPAT
25,WAHYU DWI UTOMO,LAKI - LAKI,MAHASISWA,28,BELUM MENIKAH,2.62,1.75,1.95,2.17,1.95,2.18,1.45,1.08,2.34,TEPAT
26,AHMAD FIRDAUS MABRURI,LAKI - LAKI,MAHASISWA,25,BELUM MENIKAH,2.33,3.00,2.19,0.44,2.17,0.59,0.26,NaN,1.72,TEPAT
27,HARYOKO ABDUL HAMID,LAKI - LAKI,MAHASISWA,26,BELUM MENIKAH,3.24,3.46,3.56,3.83,3.73,3.74,2.33,3.50,3.58,TEPAT
28,ERSA GILANG ARDHANI,LAKI - LAKI,MAHASISWA,25,BELUM MENIKAH,2.95,2.91,3.44,3.38,3.33,3.36,2.08,0.00,3.10,TEPAT
29,NEORITA NUR FATIMAH,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.48,3.50,2.77,3.59,3.50,3.35,3.27,0.00,3.31,TEPAT
30,ULIL ALBAB,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,2.93,3.18,3.31,3.25,3.44,3.22,3.07,3.50,3.33,TEPAT
31,DEWI KHOIRUN NISA',PEREMPUAN,MAHASISWA,27,BELUM MENIKAH,3.00,3.33,3.27,2.96,3.16,3.12,2.61,0.00,3.08,TEPAT
32,AGUS NUGROHO,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,2.83,3.11,3.10,2.96,3.20,3.53,2.48,3.00,3.27,TEPAT
33,MUKHAMAD LUQMAN HABIBI,LAKI - LAKI,MAHASISWA,25,BELUM MENIKAH,2.88,3.25,3.42,3.29,3.33,2.75,3.00,0.00,3.13,TEPAT
34,AMBAR SETIYANI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.71,3.79,3.96,3.91,3.75,3.94,2.58,4.00,3.85,TEPAT
35,AVINA SEPTIANA,PEREMPUAN,MAHASISWA,27,BELUM MENIKAH,3.07,2.85,3.20,3.00,3.21,2.47,2.55,2.75,3.10,TEPAT
36,MARIA ULFA,PEREMPUAN,MAHASISWA,24,BELUM MENIKAH,3.19,2.90,2.59,2.77,3.09,2.83,3.11,2.90,3.08,TEPAT
37,IVANDHY SETYARACHMAN,LAKI - LAKI,MAHASISWA,31,BELUM MENIKAH,2.86,2.98,3.39,3.27,2.98,2.85,2.12,NaN,3.21,TEPAT
38,CHASAN MUBAROK,LAKI - LAKI,MAHASISWA,25,BELUM MENIKAH,2.98,3.18,3.73,3.42,3.50,3.47,2.58,3.50,3.52,TEPAT
39,HASMORO ANDI WINOTO,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.26,3.33,3.73,3.41,3.46,2.94,2.65,3.00,3.47,TEPAT
40,NUR HAYATI,PEREMPUAN,MAHASISWA,23,BELUM MENIKAH,3.21,3.39,3.41,3.43,3.37,3.25,3.16,0.00,3.22,TEPAT
41,ROSIDA ARIBOWO,PEREMPUAN,MAHASISWA,24,BELUM MENIKAH,3.57,3.54,3.50,3.39,3.67,3.15,1.50,0.00,3.25,TEPAT
42,NOOR FAIZ,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,2.83,2.59,2.95,3.14,2.94,3.14,3.34,2.75,3.02,TEPAT
43,FITRIA ULFA,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.29,3.19,2.94,3.27,3.29,2.75,3.43,0.00,3.08,TEPAT
44,FANDI AHMAD,LAKI - LAKI,MAHASISWA,22,BELUM MENIKAH,3.02,3.42,3.81,3.61,3.35,3.43,3.46,4.00,3.49,TEPAT
45,FAJRI FANDILAH,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,2.55,2.57,2.57,2.82,2.64,2.33,2.34,1.80,2.86,TEPAT
46,INDAH SUSILOWATI,PEREMPUAN,MAHASISWA,28,BELUM MENIKAH,2.36,2.48,2.27,2.68,2.59,2.36,2.61,3.00,2.72,TEPAT
47,RULY WIDYASTUTI,PEREMPUAN,MAHASISWA,23,BELUM MENIKAH,2.40,2.64,2.36,2.95,2.84,2.68,2.77,2.92,2.96,TEPAT
48,AWIT RIKA JAYA KUSUMA,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,2.74,2.86,2.61,2.95,2.86,2.68,3.16,2.50,2.92,TEPAT
49,MUSLIMATUL MUFIROH,PEREMPUAN,MAHASISWA,24,BELUM MENIKAH,2.95,2.84,2.20,2.77,3.16,2.53,2.95,2.90,3.07,TEPAT

In [8]:
#menampilkan nama-nama header kolom
df.columns

Index(['NAMA', 'JENIS KELAMIN', 'STATUS MAHASISWA', 'UMUR', 'STATUS NIKAH',
       'IPS 1', 'IPS 2', 'IPS 3', 'IPS 4', 'IPS 5', 'IPS 6', 'IPS 7', 'IPS 8',
       'IPK ', 'STATUS KELULUSAN'],
      dtype='object')

In [9]:
#menghitung jumlah baris dana kolom
num_rows, num_columns=df.shape

#print jumlah
num_rows, num_columns

(145, 15)

In [14]:
df = df.drop_duplicates(subset='NAMA', keep='first')
df

,NAMA,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
0,UNAMA,LAKI - LAKI,MAHASISWA,24,BELUM MENIKAH,3.17,2.70,3.23,2.41,3.00,2.47,1.75,0.00,2.75,TEPAT
1,LEYLA TRIYANA PRATIWI,PEREMPUAN,MAHASISWA,26,BELUM MENIKAH,3.60,3.50,3.42,2.85,3.31,2.95,2.18,NaN,3.39,TEPAT
2,VERIS SOFIYAN PRAYOGA,LAKI - LAKI,MAHASISWA,29,BELUM MENIKAH,2.67,2.66,2.93,3.14,2.92,2.64,2.88,0.50,2.81,TEPAT
3,ADITYA AKBAR NUGRAHA,LAKI - LAKI,MAHASISWA,27,BELUM MENIKAH,2.48,2.86,2.09,2.55,2.55,2.43,2.55,2.17,2.82,TEPAT
4,ERNA EKA RIYANTI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.19,3.08,3.31,2.83,3.36,2.73,3.06,0.00,3.09,TEPAT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,ARY JULI SETIYANTO,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,1.98,2.50,2.14,2.77,2.61,2.93,2.82,2.50,0.99,TEPAT
141,RINA ZAHROTUL UMAMI,PEREMPUAN,BEKERJA,23,BELUM MENIKAH,2.74,2.75,2.55,3.00,2.98,2.80,3.14,3.00,2.97,TEPAT
142,TULISA WAHYUHADI KRISNATAMI,PEREMPUAN,MAHASISWA,23,BELUM MENIKAH,2.74,2.75,2.55,3.00,2.98,2.80,3.14,3.00,3.03,TEPAT
143,NI'MATUL JANNAH,PEREMPUAN,MAHASISWA,23,BELUM MENIKAH,3.02,2.94,3.25,2.87,3.00,2.94,3.09,3.00,3.16,TEPAT
144,DINDU SETYO WICAKSONO,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,3.10,3.06,3.00,3.23,2.79,3.00,2.41,3.00,2.16,TEPAT

In [15]:
#menghitung jumlah baris tersisa
jumlah_baris_tersisa=df.shape[0]
jumlah_baris_tersisa

145

In [16]:
#menghitung jumlah baris tersisa
jumlah_baris_tersisa=df.shape[1]
jumlah_baris_tersisa

15

In [18]:
#mencari baris yang mengandung missing values
baris_dengan_data_hilang=df[df.isnull().any(axis=1)]
baris_dengan_data_hilang

,NAMA,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
1,LEYLA TRIYANA PRATIWI,PEREMPUAN,MAHASISWA,26,BELUM MENIKAH,3.60,3.50,3.42,2.85,3.31,2.95,2.18,NaN,3.39,TEPAT
16,DEVI KISTIANI,PEREMPUAN,MAHASISWA,25,BELUM MENIKAH,3.52,3.46,3.69,3.41,3.40,0.00,0.00,NaN,3.43,TEPAT
26,AHMAD FIRDAUS MABRURI,LAKI - LAKI,MAHASISWA,25,BELUM MENIKAH,2.33,3.00,2.19,0.44,2.17,0.59,0.26,NaN,1.72,TEPAT
37,IVANDHY SETYARACHMAN,LAKI - LAKI,MAHASISWA,31,BELUM MENIKAH,2.86,2.98,3.39,3.27,2.98,2.85,2.12,NaN,3.21,TEPAT
99,YUIKE WIJAYANTI,PEREMPUAN,MAHASISWA,24,BELUM MENIKAH,2.55,3.07,2.68,3.00,3.25,3.08,3.18,0.0,NaN,TEPAT
102,MUSTAANUN NA'IM,LAKI - LAKI,MAHASISWA,23,BELUM MENIKAH,3.05,3.19,3.52,3.57,3.25,3.79,2.50,4.0,NaN,TEPAT
112,FITRI KOMALASARI,PEREMPUAN,MAHASISWA,26,BELUM MENIKAH,2.79,3.09,3.08,2.96,2.59,3.19,3.38,3.0,NaN,TEPAT

In [23]:
#mencari kolom yang mengandung missing values
kolom_dengan_data_hilang=df.columns[df.isnull().any()]
kolom_dengan_data_hilang

Index(['IPS 8', 'IPK '], dtype='object')